### ISSUE TITLE
suggestion: align spawn and islands to region file centers

### ISSUE THREAD

**Issue by LoyLT** [TheCricket/FTB-Islands#13] opened 2016-04-04 00:20 UTC
not sure if this change would be safe for existing worlds... but 

center the world spawn point at 256,256 instead of 0,0..... 256,256 would be the center of region file 0,0

and then spawned islands should appear at 1024 intervals from there... so that the center of the islands are centered in their own region files

or... have the world center and the spacing interval configurable by admins

**Comment by TheCricket** [comment] 2016-04-04 00:21
duplicate of another issue

**Comment by StoneLegion** [comment] 2016-04-04 00:21
I guess this is better then #12

**Closed as completed by TheCricket** 2016-04-04 00:21 UTC
